services:
  tasker:
    build: .
    image: lalkl4/tasker:latest
    container_name: tasker
    ports:
      - "8000:8000"
    volumes:
      - tasker-data:/app/data
    restart: unless-stopped

volumes:
  tasker-data:
